# Generated by Django 6.0.2 on 2026-02-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GuildRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.guild')),
                ('permissions', models.ManyToManyField(to='backend.botpermission')),
            ],
        ),
    ]
