# Generated by Django 6.0.2 on 2026-03-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_discordmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildrolepermission',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='backend.guildrolepermission'),
        ),
    ]
