# Generated by Django 6.0.2 on 2026-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_guildrolepermission_name_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
