# Generated by Django 6.0.2 on 2026-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_channel_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmessage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='discord_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
